name: Pull Request
run-name: ${{ github.actor }} made a pull request
on:
  pull_request:
    types: [opened, reopened]
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: "21"
      - run: npm install -g bats
      - run: bats -v
